### PR TITLE
Windows 10 evaluation template

### PR DESCRIPTION
**Pull request by 10Peppermill**
I've created a windows 10 enterprise packer template that uses an enterprise evaluation .iso to create a MaaS deploy-able UEFI image. This template was tested using a 22H2 build of windows 10 enterprise evaluation and was deployed to a supermicro X10SRL-F equipped system.

### CODE REVIEW

**Comment by camille-rodriguez** [comment]
Hi, any update on this work ? It would be really useful to get this in the main branch

**Comment by sempervictus** [comment]
Are there any blockers to merging this?

**Comment by camille-rodriguez** [comment]
I've been informed that the main work for Windows images has been focused in the branch [<windows>](https://github.com/canonical/packer-maas/tree/windows) and that branch should be the one submitted for PR

**Comment by alexsander-souza** [comment]
A Windows template has been merged to `main`, please check if this is suitable for your use.

**Pull request closed without merging**
