### PR TITLE
Windows templates

### PR DESCRIPTION
**Pull request by g-ramirez**
Added windows templates for creating uefi Windows images

### CODE REVIEW

**Comment by g-ramirez** [comment]
Hey Adam,

I have confirmed this works with windows 2016.  If you have access to salesforce, here would be the steps to do so:
https://canonical.lightning.force.com/lightning/r/Knowledge__kav/ka44K000000c15fQAA/view

Best,
Gabe

**Comment by alexsander-souza** [comment]
Hey, great work. Before we land this we need to add a README file explaining what people should expect from this template, what they need to supply (e.g. where to put the ISO), what kind of customization it allows and how to upload it to MAAS. You can use https://github.com/canonical/packer-maas/blob/master/ubuntu/README.md as reference.

**Review by alexsander-souza — CHANGES_REQUESTED** [review]
Hey, great work. Before we land this we need to add a README file explaining what people should expect from this template, what they need to supply (e.g. where to put the ISO), what kind of customization it allows and how to upload it to MAAS. You can use https://github.com/canonical/packer-maas/blob/master/ubuntu/README.md as reference.

**Comment by neofob** [comment]
@g-ramirez : Thanks for sharing this. I use this patch with other changes from [`packer-windows`][0] to build a MaaS image of Windows 2019 HyperV.

However, I notice that the script [`logon.ps1:139`][1] has a missing command after installing Cloudbase-Init and running `SetSetupComplete.cmd`. Basically, the below lines need to be added before running `Sysprep.exe`:

```
$Host.UI.RawUI.WindowTitle = "Running SetupComplete.cmd"
& "C:\Windows\Setup\Scripts\SetupComplete.cmd"
```

[1]: https://github.com/g-ramirez/packer-maas/blob/master/windows/http/logon.ps1#L139
[0]: https://github.com/StefanScherer/packer-windows

**Comment by simeononsecurity** [comment]
@alexsander-souza @neofob Any updates on this?

**Comment by nicfries** [comment]
We based our Windows Server 2022 image off this. Merging this would be nice and preferred over MAAS Image Builder.

**Comment by alexsander-souza** [comment]
> We based our Windows Server 2022 image off this. Merging this would be nice and preferred over MAAS Image Builder.

@nicfries , can you share your changes to get this working for win2022?

**Comment by nicfries** [comment]
Hi Alexsander, yes I can upstream those changes.

**Comment by sparkiegeek** [comment]
> Hi Alexsander, yes I can upstream those changes.

Any chance you could push these somewhere @nicfries ?

**Comment by r00ta** [comment]
Hey @nicfries ! Did you make any progress on this?

**Comment by SK1Y101** [comment]
Hey @g-ramirez, could you revisit this and add the requested README? that would be awesome!
and @nicfries just checking in on changes needed to deploy win22, are they available anywhere at all?

**Comment by g-ramirez** [comment]
> Hey @g-ramirez, could you revisit this and add the requested README? that would be awesome! and @nicfries just checking in on changes needed to deploy win22, are they available anywhere at all?

Let me see what I can do,  I was working with Canonical at the time I proposed the changes and I haven't had time to review this fully and I'm also really busy these days, but I'll post back by the end of the week

**Comment by alexsander-souza** [comment]
We moved this to a feature branch where the community can contribute to complete this work.

**Pull request closed without merging**
