### PR TITLE
Add support for Rocky 9

### PR DESCRIPTION
**Pull request by jurekh**
This PR adds support for Rocky 9. Note that it requires the upcoming MAAS 3.2.1 with Curtin 22.1, or a patched Curtin version - this is clearly indicated in the readme file.

### CODE REVIEW

**Comment by lwandrebeck** [comment]
Hello,
```
diff --git a/rocky9/rocky9.json b/rocky9/rocky9.json
index 3f842dd..675660a 100644
--- a/rocky9/rocky9.json
+++ b/rocky9/rocky9.json
@@ -18,12 +18,11 @@
             ],
             "boot_wait": "3s",
             "disk_size": "4G",
-            "headless": false,
+            "headless": true,
             "memory": 2048,
             "http_directory": "http",
             "qemuargs": [
-                [ "-serial", "stdio" ],
-                [ "-cpu", "host" ]
+                [ "-serial", "stdio" ]
             ],
 
             "shutdown_timeout": "1h"
```
helps. Can’t get much farther though, as I’m hitting
Qemu stdout: Fatal glibc error: CPU does not support x86-64-v2
HTH !

**Comment by jurekh** [comment]
I see that the `[ "-cpu", "host" ]` entry is removed - that's what helped avoid the error related to x86-64-v2. Have you tried adding that back?

And thanks for spotting that I left the headless mode disabled, it's fixed now.

**Comment by lwandrebeck** [comment]
With -cpu host I get Qemu stderr: qemu-system-x86_64: CPU model 'host' requires KVM or HVF but that’s probably due to my particular setup.

**Comment by jurekh** [comment]
The readme file specifies that you need "A machine running Ubuntu 18.04+ with the ability to run KVM virtual machines and with a CPU that supports x86-64-v2 extensions", so unfortunately you may need to use another host to build the image. 

Also, let's keep this thread related to the PR, which is adding support for Rocky 9. Please share here things that don't work when you try it on a system that meets the requirements, or if you have review remarks.

**Comment by lwandrebeck** [comment]
Indeed. After fixing my setup, everything went fine, image has just been uploaded to MAAS.
Thanks !

**Comment by lwandrebeck** [comment]
I can’t get RL9 to properly install. Using snap 3.2/edge, curtin is up to date enough.
```
Name  Version                  Rev    Tracking  Publisher   Notes
maas  3.2.0-11994-g.e45209c7b  22766  3.2/edge  canonical✓  -
```
Installs go nicely (storage config, OS config etc), but MAAS is stuck at the "rebooting" phase.
Any idea ?

**Comment by jurekh** [comment]
@lwandrebeck is the curtin version that MAAS uses patched according to the readme file? Until MAAS includes curtin 22.1, you need to patch one file manually to get Rocky to deploy.

**Comment by lwandrebeck** [comment]
```
root@maas:~# grep rocky /snap/maas/22860/usr/lib/python3/dist-packages/curtin/distro.py
                'rocky']
                     DISTROS.rhel, DISTROS.rocky],
```
So I guess we’re fine on that point.
I try to provision baremetal server, maybe we hit that point according to C8/C8S kickstart:
```
# grub2-efi-x64 ships grub signed for UEFI secure boot. If grub2-efi-x64-modules
# is installed grub will be generated on deployment and unsigned which breaks
# UEFI secure boot.
```
But I’ve tested commenting out `grub2-efi-x64-modules` without success.
I’ll check machine KVM as soon as possible, unfortunately, IPMI web UI of this machine is flacky and will need a bit of external programmer. As that’s out of my league, it could take a while.

**Comment by sparkiegeek** [comment]
This will need converting to HCL (see #61) and re-basing

**Comment by alexsander-souza** [comment]
superseded by #66

**Pull request closed without merging**
